[workspace]
resolver = "3"
members = [
    "crates/pulsar-common",
    "crates/pulsar-api",
    "crates/pulsar-auth",
    "crates/pulsar-gateway",
    "crates/pulsar-messaging",
    "crates/pulsar-db",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"


[workspace.dependencies]
tokio = { version = "1", features = ["full", "sync"] }
axum = { version = "0.8", features = ["ws", "macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
thiserror = "2"
anyhow = "1"
argon2 = { version = "0.5", features = ["std"] }
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
futures = "0.3"
async-nats = "0.46.0"
bytes = "1.11.1"
tower-http = { version = "0.6", features = ["cors"] }
sqlx = { version = "0.8", features = [
    "runtime-tokio",
    "tls-rustls",
    "postgres",
    "chrono",
    "migrate",
] }
