[package]
name = "pulsar-api"
version.workspace = true
edition.workspace = true

[dependencies]
pulsar-common = { path = "../pulsar-common" }
pulsar-auth = { path = "../pulsar-auth" }
pulsar-db = { path = "../pulsar-db" }
pulsar-storage = { path = "../pulsar-storage" }
pulsar-crypto = { workspace = true }
pulsar-scylla = { workspace = true }
deadpool-redis = { workspace = true }
redis = { workspace = true }
tokio.workspace = true
axum.workspace = true
axum-extra.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
chrono.workspace = true
tower-http.workspace = true
sqlx.workspace = true
jsonwebtoken.workspace = true
anyhow.workspace = true
dotenvy.workspace = true
uuid.workspace = true
sha2 = { workspace = true }
time = { workspace = true }
infer = "0.16"